# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/imperator/Code/RecRepEvent/HW/EventRecRep.srcs/sources_1/ip/dist_mem_gen_3/dist_mem_gen_3.xci
# IP: The module: 'dist_mem_gen_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/imperator/Code/RecRepEvent/HW/EventRecRep.gen/sources_1/ip/dist_mem_gen_3/dist_mem_gen_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/imperator/Code/RecRepEvent/HW/EventRecRep.srcs/sources_1/ip/dist_mem_gen_3/dist_mem_gen_3.xci
# IP: The module: 'dist_mem_gen_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/imperator/Code/RecRepEvent/HW/EventRecRep.gen/sources_1/ip/dist_mem_gen_3/dist_mem_gen_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
