_wandb:
    value:
        cli_version: 0.19.9
        m:
            - "1": gradients/decoder.gru2.linear_hh.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": gradients/decoder.linear.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/encoder.gru1.linear_hh.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/encoder.gru2.linear_hh.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.linear.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.gru1.linear_ih.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.gru1.linear_hh.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.gru1.linear_ih.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.linear.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.gru2.linear_ih.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.output2hidden.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.output2hidden.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_pol
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.gru2.linear_ih.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.gru1.linear_hh.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/encoder.gru1.linear_ih.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.output2hidden.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.output2hidden.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/encoder.gru2.linear_ih.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.gru1.linear_hh.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/encoder.gru1.linear_ih.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/encoder.gru2.linear_hh.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/encoder.gru1.linear_hh.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/encoder.gru1.linear_ih.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.gru1.linear_hh.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.gru2.linear_hh.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/encoder.gru1.linear_hh.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.linear.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.gru2.linear_hh.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.gru1.linear_ih.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.gru1.linear_ih.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.gru2.linear_ih.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.gru2.linear_ih.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/encoder.gru2.linear_hh.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_time
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.gru2.linear_hh.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/encoder.gru2.linear_ih.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.gru1.linear_hh.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.gru1.linear_hh.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.gru2.linear_ih.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/encoder.gru2.linear_hh.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.output2hidden.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/encoder.gru2.linear_ih.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.gru2.linear_hh.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/encoder.gru2.linear_hh.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/encoder.gru1.linear_hh.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/encoder.gru1.linear_ih.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.output2hidden.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/encoder.gru2.linear_ih.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.linear.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.gru2.linear_ih.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/encoder.gru1.linear_ih.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/encoder.gru2.linear_ih.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.gru2.linear_hh.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/encoder.gru1.linear_ih.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.gru1.linear_ih.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/encoder.gru2.linear_ih.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.gru1.linear_ih.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/encoder.gru1.linear_hh.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/decoder.linear.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/encoder.gru2.linear_hh.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/encoder.gru1.linear_hh.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 55
                - 106
            "2":
                - 1
                - 55
                - 106
            "3":
                - 1
                - 7
                - 13
                - 23
                - 55
                - 62
                - 66
            "4": 3.12.2
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
