name: Gen1
data_dir: /net/storage/pr3/plgrid/plgg_dvs_phd/Detection/gen1
dir_to_save: /net/scratch/hscra/plgrid/plgjeziorek/Datasets/gen1_processed

sensor_size:
  W: 304
  H: 240
image_size:
  W: 224
  H: 224
time_window: 200000
num_events: 50000

encoder:
  rnn_type: MyGRU
  input_size: 1         # 1 if only timestamps, 2 if timestamps + polarity
  hidden_size: [12, 12, 12]
  num_bits: 8
  input_num_bits: 12
decoder:
  rnn_type: MyGRU
  hidden_size: [12, 12, 12]

train_encoder:
  scale_time_loss: 1
  scale_polarity_loss: 0.1
  learning_rate: 0.001
  weight_decay: 0.0001

remove_empty_pixels: true
crop_events_spatially: true
crop_window: 64

apply_psee_bbox_filter: true
apply_faulty_bbox_filter: true

representation: Encoder
encoder_checkpoint: /net/scratch/hscra/plgrid/plgjeziorek/checkpoints/best_model_MyGRU_calibrated.ckpt

num_processes: 8    # number of processes to use for data generation
num_workers: 16      # number of workers to use for data loading
batch_size: 64

augmentation:
  h_flip: 0.5